# theme: jekyll-theme-cayman

# theme: https://just-the-docs.github.io/just-the-docs/
remote_theme: just-the-docs/just-the-docs
title: 기미나인(Gimi9) 설명서
description: CSV, XLSX 미리보기, 데이터 품질 검사 리포트 (Pandas Profiling Report), 지도에서 보기, 주소 품질 검사

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 3


